# sql schema

# --- !Ups
CREATE TABLE IF NOT EXISTS USER(
  ID VARCHAR NOT NULL PRIMARY KEY,
  NAME VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS GAME(
		ID VARCHAR NOT NULL PRIMARY KEY,
		NAME VARCHAR NOT NULL,
		YEAR_PUBLISHED INT,
		IMAGE_URL VARCHAR NOT NULL,
		SUBTYPE VARCHAR,
	  MIN_PLAYERS INT,
		MAX_PLAYERS INT,
		MIN_PLAYTIME INT,
		MAX_PLAYTIME INT,
		PLAYING_TIME INT,
		NUM_OWNED INT,
		RATING_COUNT INT,
		AVERAGE_RATING DOUBLE,
		BAYES_AVERAGE_RATING DOUBLE,
		STD_DEV_RATING DOUBLE,
		MEDIAN_RATING DOUBLE);

CREATE TABLE IF NOT EXISTS USER_COLLECTION(
		ID VARCHAR NOT NULL PRIMARY KEY,
		USER_ID VARCHAR NOT NULL,
    GAME_ID VARCHAR NOT NULL,
		NUM_PLAYS INT,
		OWN BOOL,
		PREV_OWNED BOOL,
		FOR_TRADE BOOL,
		WANT BOOL,
	  WANT_TO_PLAY BOOL,
		WANT_TO_BUY BOOL,
		WISHLIST BOOL,
		WISHLIST_PRIORITY INT,
		PRE_ORDERED BOOL,
		LAST_MODIFIED VARCHAR,
		USER_RATING DOUBLE,
    FOREIGN KEY (USER_ID) REFERENCES USER(ID),
    FOREIGN KEY (GAME_ID) REFERENCES GAME(ID));

CREATE TABLE IF NOT EXISTS GLOBAL_SETTING(KEY VARCHAR NOT NULL PRIMARY KEY, VALUE VARCHAR NOT NULL);

# --- !Downs

DROP TABLE USER_COLLECTION;
DROP TABLE GLOBAL_SETTING;
DROP TABLE GAME;
DROP TABLE USER;
